// Fictional presentation content only. Never seed the production database.
export const demoEvents = [
  {
    title: "לילה בכותל, יחד",
    subtitle: "ירושלים באור אחר. לילה של תפילה, חיבור וביחד.",
    category: "מפגש לילי · לנשים בלבד",
    location: "הכותל המערבי, ירושלים",
    address: "הכותל המערבי, ירושלים",
    price: 0,
    capacity: null,
    days: 14,
    asset: "public/demo/women-kotel-night.webp",
    description:
      "מפגש לילי לנשים בכותל המערבי, באווירה של תפילה, חיבור וביחד.\n\nפרטי המפגש המלאים יעודכנו על ידי המנהלת.",
  },
  {
    title: "פורים שלנו",
    subtitle: "מסיבת תחפושות לנשים. באות לשמוח, ביחד.",
    category: "מסיבת פורים · לנשים בלבד",
    location: "המיקום יעודכן בהמשך",
    address: "",
    price: 0,
    capacity: null,
    days: 21,
    asset: "public/demo/women-purim.webp",
    description:
      "מסיבת פורים לנשים בלבד — עם תחפושות, שמחה ואווירה חגיגית.\n\nבחרי את התחפושת שלך, ובואי לחגוג איתנו. פרטי התוכנית והמיקום יעודכנו על ידי המנהלת.",
  },
  {
    title: "שיעור עם הרבנית",
    subtitle: "ערב של תורה, שאלות אמיתיות ולב פתוח.",
    category: "שיעור תורה · לנשים בלבד",
    location: "המיקום יעודכן בהמשך",
    address: "",
    price: 0,
    capacity: null,
    days: 28,
    asset: "public/demo/event-torah.webp",
    assetWide: "public/demo/event-torah-wide.webp",
    description:
      "שיעור תורה לנשים עם רבנית אורחת, על פרשת השבוע ועל החיים שבתוכה.\n\nמגיעות כמו שאתן, בלי ידע מוקדם. יש זמן לשאלות, יש כיבוד קל, ויש עם מי לדבר אחרי. פרטי השיעור והמיקום יעודכנו על ידי המנהלת.",
  },
  {
    title: "הפרשת חלה",
    subtitle: "בצק, ברכה, ונשים שמברכות ביחד.",
    category: "הפרשת חלה · לנשים בלבד",
    location: "המיקום יעודכן בהמשך",
    address: "",
    price: 40,
    capacity: 30,
    days: 35,
    asset: "public/demo/event-challah.webp",
    assetWide: "public/demo/event-challah-wide.webp",
    description:
      "ערב הפרשת חלה לנשים: לשות יחד, מברכות יחד, וכל אחת חוזרת הביתה עם חלות משלה.\n\nהעלות מכסה את חומרי הגלם. המקומות מוגבלים, ולכן ההרשמה מראש. הפרטים המלאים יעודכנו על ידי המנהלת.",
  },
  {
    title: "ערב העצמה נשית",
    subtitle: "לעצור לרגע, להקשיב לעצמך, ולצאת עם משהו חדש.",
    category: "ערב העצמה · לנשים בלבד",
    location: "המיקום יעודכן בהמשך",
    address: "",
    price: 60,
    capacity: 80,
    days: 42,
    asset: "public/demo/event-empowerment.webp",
    assetWide: "public/demo/event-empowerment-wide.webp",
    description:
      "ערב העצמה לנשים עם מרצה אורחת, סדנה קצרה ושיחה פתוחה.\n\nערב שמתחיל בהרצאה וממשיך במעגל שיחה קטן, כדי שכל אחת תצא עם תובנה אחת שלה. פרטי הערב, המרצה והמיקום יעודכנו על ידי המנהלת.",
  },
];
